Draft: [GraphQL October 2021] Forbid `__typename` on subscription root
graphql-rust/juniper pull request #1001
Opened 2021-12-08 13:17 UTC by ilslv

Part of #1000

## Synopsis

TODO

## Solution

TODO

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2021-12-09 12:11 UTC, ilslv commented
## FCM

```
Forbid `__typename` on subscription root (#1001)
```

2021-12-09 14:27 UTC, tyranron requested changes
Anything else seems good.

2021-12-09 14:27 UTC, tyranron commented on juniper/src/validation/rules/fields_on_correct_type.rs
> +                    if field.item.name.item == "__typename" {
We should add tests fully covering this in this module below along with others.

2021-12-13 11:26 UTC, tyranron approved these changes
Anything else is nice 👍

2021-12-13 11:26 UTC, tyranron commented on juniper_actix/Cargo.toml
> +actix-http = "3.0.0-beta.15"
Please, disolve such thing to a separate PR next time.

2021-12-13 12:27 UTC, merged