Draft: Allow `#[derive(GraphQLInterface)]` and `#[graphql_interface]` on structs
graphql-rust/juniper pull request #1026
Opened 2022-02-21 12:32 UTC by ilslv

## Synopsis

After #1009 GraphQL interfaces are represented with traits acting as blueprints for methods names, arguments and return types.

## Solution

To emphasise structural nature of GraphQL interfaces, allow representing them with structs:

```rust
#[derive(GraphQLInterface)]
#[graphql(for = Human)]
struct Character {
    id: String,
}
```

```rust
#[graphql_interface(for = Human)]
struct Character {
    id: String,
}
```

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [ ] Documentation is updated (if required)
- [ ] Tests are updated (if required)
- [ ] Changes conform code style
- [ ] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2022-03-10 12:13 UTC, ilslv commented
## FCM

```
Implement `#[derive(GraphQLInterface)]` to use structs as GraphQL interfaces (#1026)

- support `#[graphql_interface]` on structs
```

2022-03-11 16:18 UTC, tyranron requested changes
@ilslv overall good, but requires a little bit of polishing though.

2022-03-11 16:18 UTC, tyranron commented on juniper_codegen/src/graphql_interface/attr.rs
> +    ERR.emit_custom(span.span(), "expected named struct field");
I don't see this case covered in codegen failure tests. Please, add.

2022-03-11 16:18 UTC, tyranron commented on juniper_codegen/src/graphql_interface/derive.rs
> +        |c| format_ident!("{}Enum", c.inner().to_string()),
This code has become quite repetitive, so can be DRYed and factored out into a separate function for reusing.

2022-03-11 16:18 UTC, tyranron commented on juniper_codegen/src/graphql_interface/derive.rs
> +fn err_unnamed_field<T, S: Spanned>(span: &S) -> Option<T> {
Meh... do not duplicate code. Just reuse the one from a neigbour module.

2022-03-25 06:52 UTC, ilslv commented
@tyranron CI build on nightly fails because of https://github.com/briansmith/ring/issues/1469 and from what I can tell this is a bug in recent nightly version and how it handles doc comments inside decl macros https://github.com/briansmith/ring/pull/1470

2022-04-01 15:50 UTC, tyranron approved these changes

2022-04-01 18:10 UTC, merged