Fix content-header parsing in juniper_axum
graphql-rust/juniper pull request #1289
Opened 2024-10-24 22:51 UTC by jgrund

Check media type using `starts_with` instead of full string matching.

Fixes #1288

2024-10-25 12:55 UTC, LegNeato requested changes
Thank you for the great report and the PR! 🍻 

Two quick things:
1. Can you add an entry to the `CHANGELOG`?
2. Can you add a test so we don't regress this in the future? (if it is too hard / will take too much time, please feel free to comment as such!)

2024-10-26 08:37 UTC, LegNeato approved these changes
Thanks again!

2024-10-26 08:38 UTC, merged

2024-10-26 18:42 UTC, jgrund commented
Thank you, can we cut a new release of `juniper_axum` with this fix?

2024-10-28 12:10 UTC, tyranron commented
@jgrund thank you for the PR!

Backported and released as 0.1.1: https://crates.io/crates/juniper_axum/0.1.1