Allow disabling camelCase convertion
graphql-rust/juniper pull request #765
Opened 2020-09-16 15:01 UTC by ip1981

Add a new attribute `rename` which could be "none", "camelCase", "SCREAMING_SNAKE_CASE".
By default (when this attribute is not specified) the exiting rules apply: camelCase to structs, SCREAMING_SNAKE_CASE to enums.

This does not change interfaces because I haven't figured how to do them yet.

Re https://github.com/graphql-rust/juniper/issues/201.

2020-09-17 05:27 UTC, LegNeato requested changes
Thanks for the PR, this looks great! A couple of changes / suggestions:

1. We'll need a couple of unit tests or integration tests to make sure this isn't broken in the future.
2. I'd prefer to match the API from http://serde.rs. that is, `rename` in a field is for a specific name set verbatim and the ability to use a rename strategy at the top-level is on the object definition.

2020-09-17 10:50 UTC, ip1981 commented
I'm not sure I totally get the second point.

There are differences between juniper and serde:

1. Juniper in fact uses only one-way renaming, even when decoding input objects. This is why there is no point in having an attribute like `rename_all`, for example.
2. I am trying to keep existing behavior by default (camelCase for structs, SCREAMING_CASE for enums). That's why it is `Option<RenameRule>`.

Each struct member already can be renamed explicitly with the `name` attribute.

2020-09-17 10:51 UTC, ip1981 commented
I will add some tests for sure :)

2020-09-18 05:36 UTC, LegNeato commented
Ugh, sorry...read that way too fast and was fried from work. You're right, ignore #2 :-)

2020-09-27 13:57 UTC, ip1981 commented
Added some tests.

2020-10-01 05:51 UTC, LegNeato commented
Thank you! I'll land this in a couple of days.

2020-10-13 10:04 UTC, mkpankov commented
Hey! Any updates on this?

2020-10-13 16:34 UTC, LegNeato approved these changes

2020-10-13 16:34 UTC, merged