Allow raw identifier for field arguments
graphql-rust/juniper pull request #812
Opened 2020-11-24 12:57 UTC by zaksabeast

Fixes #786.

This pull request allows raw identifiers to be used for field arguments, and updates `multi_args_descr_trailing_comma` to include a trailing comma.

2020-11-24 14:31 UTC, tyranron requested changes
@zaksabeast thank you!

Would you be so kind to re-check that for GraphQL interfaces and add appropriate tests to `integration_tests/juniper_tests/` too?

2020-11-24 15:41 UTC, zaksabeast commented
@tyranron Sure thing!

I'd be happy to do the re-check and add integration tests.

Could you please elaborate on the ask to re-check GraphQL interfaces?  I'm not super familiar with Juniper and might be misunderstanding the ask, so correct me if I'm wrong, but it looks like `arguments` can't currently be used with methods of a trait using the `graphql_interface` proc macro.

Would adding a test to `integration_tests/juniper_tests/src/codegen/derive_object_with_raw_idents.rs` make sense, or would a new file be preferred?

2020-11-25 08:23 UTC, tyranron commented
@zaksabeast 

> it looks like `arguments` can't currently be used with methods of a trait using the `graphql_interface` proc macro.

Hmmm, right. I didn't figure it out. So, `#[graphql_interface]` doesn't have such problem at all.

> Would adding a test to `integration_tests/juniper_tests/src/codegen/derive_object_with_raw_idents.rs` make sense, or would a new file be preferred?

It would be better to add `mod raw_arguments` to the `integration_tests/juniper_tests/src/codegen/impl_object.rs`, like [`fallible` does](https://github.com/graphql-rust/juniper/blob/a4871887bb6b30029bd4671af716c0649a0cc60c/integration_tests/juniper_tests/src/codegen/impl_object.rs#L85-L96).

Thanks!

2020-11-25 14:17 UTC, zaksabeast commented
Perfect, thank you for the help!

2020-11-26 10:44 UTC, tyranron approved these changes
@zaksabeast thanks! 🍻

2020-11-26 10:46 UTC, merged