remove jsdelivr versioning of graphql-playground
graphql-rust/juniper pull request #854
Opened 2021-01-22 03:57 UTC by dt665m

This is a fix for #853

2021-01-22 09:27 UTC, tyranron requested changes
@dt665m thanks for the contribution!

2021-01-22 09:27 UTC, tyranron commented on juniper/src/http/playground.rs
> +  <script src="//cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js"></script>
I don't think that removing the version at all is a good way to go, as it's the same as have `tokio = "*"` in `Cargo.toml`. You will never now when the things blew up on breaking change.

But!

We can just follow semver and specify `@1` version. So we catch up with recent updates but don't hit major version breakage.

2021-01-22 09:27 UTC, tyranron commented on juniper/src/http/playground.rs
>    <link rel="shortcut icon" href="//cdn.jsdelivr.net/npm/graphql-playground-react/build/favicon.png" />
And it seems that here and in the line above we should specify `@1` version too.

2021-01-23 05:28 UTC, Zireael13 commented
Sorry didn't see this PR before I created #856. As I noted there, just using the latest version (currently 1.7.27) won't work as that is the one that is broken. Need to pin it to 1.7.26 which I did in the other PR. Can move the changes over here if you'd like @tyranron

2021-01-25 10:45 UTC, dt665m commented
> Sorry didn't see this PR before I created #856. As I noted there, just using the latest version (currently 1.7.27) won't work as that is the one that is broken. Need to pin it to 1.7.26 which I did in the other PR. Can move the changes over here if you'd like @tyranron

for some reason, leaving out the semver on jsdeliver resolves to a working version.  We're running off my PR here and it works.  🤷‍♂️

2021-01-25 14:58 UTC, Zireael13 commented
> for some reason, leaving out the semver on jsdeliver resolves to a working version. We're running off my PR here and it works. 🤷‍♂️

https://cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js

Huh you are right. That is really odd. jsDelivr must somehow resolve to a past version if the file isn't present in the new one, I guess.

I guess we'll leave it up to the repo maintainers if they want to go with the versionless one or pinned to 1.7.26.

2021-01-26 08:37 UTC, LegNeato commented
Generally I like explicit versioning as it helps reproducible builds as well as tracking down bugs. Thank you for the PR!

2021-01-26 08:37 UTC, closed without merging