Support subscriptions for GraphiQL and Playground.
graphql-rust/juniper pull request #859
Opened 2021-01-25 15:37 UTC by alvra

Add support for subscriptions for GraphiQL and Playground in `juniper_rocket_async`.

Note this changes the function signatures. Since the crate hasn't been release I'm not sure about backwards compatibility concerns. At least the signatures are consistent now.

2021-02-02 06:50 UTC, LegNeato requested changes
Thank you for the PR! The CI failures look legit sadly:

```
juniper_rocket_async/examples/rocket_server.rs:11:5
   |
11 |     juniper_rocket_async::graphiql_source("/graphql")
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---------- supplied 1 argument
   |     |
   |     expected 2 arguments
   |
note: function defined here
  --> /home/vsts/work/1/s/juniper_rocket_async/src/lib.rs:72:8
   |
72 | pub fn graphiql_source(
   |        ^^^^^^^^^^^^^^^

error: aborting due to previous error
```

2021-02-02 11:42 UTC, alvra commented
I've updated the example. Hope everything goes green now :)

2021-02-02 12:05 UTC, alvra commented
Looks like it's hitting compiler errors on nightlies. I guess that's not related...

2021-02-04 02:17 UTC, LegNeato commented
Yep, looks like a bug in Nightly. Thank you for polishing this up! 🍻

2021-02-04 02:17 UTC, merged