Update juniper_codegen for syn 1.0.60
graphql-rust/juniper pull request #861
Opened 2021-01-25 16:49 UTC by obmarg

syn 1.0.60 has updated it's `Type::__Nonexhaustive` to
`Type::TestExhaustive`, breaking juniper.  This updates juniper to use
the recommended idiom for doing exhaustive matching on `Type`, which
fixes this.

Not entirely clear if we need exhaustive matching here or if we could
just use a fallback, but this fixes the build at least.

Though I imagine this will break if users are still on an old syn - not
sure how to manage that.

Fixes #858

2021-01-25 17:04 UTC, obmarg commented
Also updated an example `Cargo.toml` to use path based deps for juniper as otherwise it pulled the broken code from github - let me know if that's not the right thing to do.

2021-01-25 20:25 UTC, Binero commented
For now this can be worked around by adding an explicit dependency to `syn = "=1.0.59` in your `Cargo.toml`. 

```toml
[dependencies]
actix-web = "3.3"
juniper = "0.15.2"
syn = "=1.0.59"
```

2021-01-26 00:52 UTC, trevyn commented
> I imagine this will break for users who are still on an old syn though.

We could just specify `syn` `1.0.60` in `juniper_codegen/Cargo.toml`, right? Technically that’s not a breaking change...

2021-01-26 08:33 UTC, LegNeato commented
Thank you for this! I think we should change it to 1.0.60 as that is now the min required version, correct?

2021-01-26 08:34 UTC, LegNeato requested changes
As mentioned, I think we want cargo.toml changes

2021-01-26 10:15 UTC, obmarg commented
Updated the Cargo.toml

2021-01-26 17:41 UTC, merged

2021-01-26 17:41 UTC, LegNeato commented
Thank you! I'll get a crates.io to release out later tonight

2021-01-27 01:32 UTC, kitsuneninetails commented
Please push crate ASAP, as this completely derails our entire production-level application builds.  :pray: 

Thanks!

2021-01-28 08:02 UTC, LegNeato commented
This is now on crates.io