Make the executor and validation APIs public to enable split parsing and execution
graphql-rust/juniper pull request #874
Opened 2021-02-13 02:01 UTC by jerel

Making these APIs public is based on my understanding of https://github.com/graphql-rust/juniper/pull/773#issuecomment-703783048 and https://github.com/graphql-rust/juniper/pull/773#issuecomment-704009918

This PR is related to #776, #726, and enables features similar to #843 to be implemented in user land code. In my project I'm currently doing this (pseudo code) in the first step:
``` rust
fn compile() {
  let document = parse_document_source(document_source, &root_node.schema)?;
  visit_all_rules(&mut ctx, &document);
  let operation = get_operation(&document, operation_name)?;
  Ok((document.clone(), operation.clone()))
}
```
so I can make use of the `operation` and `document` and then in the second step I'm using the [now public] `validation::validate_input_values` and `executor::execute_validated_query_async` or `resolve_validated_subscription` as needed.

Thoughts on these changes?

2021-03-04 17:44 UTC, jerel commented
@LegNeato @ccbrown what are your thoughts on this proposed change?

Being able to precompile queries while checking them against the schema is a big requirement of a project I'm working on and ideally we could implement it in a way that stays aligned with this project.

2021-03-04 18:54 UTC, ccbrown commented
To sum up my thoughts from the linked issues:

* This is really valuable functionality that we should have in some form.
* Ideally parsing wouldn't require knowledge of the schema. Unfortunately this eliminating the parser's dependency on the schema isn't trivial. @mirosval made a valiant effort in https://github.com/graphql-rust/juniper/pull/782, but it fell through. Given the value of this functionality and the lack of a clear path towards eliminating the parser's schema dependency, I'm okay moving forward with exposing whatever's necessary for this functionality anyway.
* I have a preference for exposing this functionality in the inner crates (`juniper::parser`, `juniper::validation`, etc.) rather than the top level `juniper` crate, just for the sake of keeping the top level API narrow.

2021-04-02 04:09 UTC, LegNeato requested changes
Sorry this took so long. Can you add an integration test that uses the API so we can be sure to not regress?

2021-04-03 05:12 UTC, LegNeato approved these changes
Thank you! 🍻

2021-04-03 05:13 UTC, merged

2021-04-04 01:56 UTC, LegNeato commented
This is now on crates.io. Thank you again!

2022-06-19 23:45 UTC, mrtnzlml commented
Hey @jerel! 👋 I have a question regarding this PR. Say you want to implement persistent queries, so in the first step, you parse and validate the query and save it to DB (so it can be accessed later while skipping validations). My question is: how should the validated query be stored in DB? Do you store it as a string (meaning that you must call `parse_document_source` later again)? Or is there a better way to skip the parsing on future requests? Thanks! :)